feat(file): client CRUDL
IBM/ibm-generative-ai-node-sdk pull request #36
Opened 2023-07-17 10:23 UTC by pilartomas

2023-07-18 07:26 UTC, pilartomas commented on src/api-types.ts
> +export const FilePurposeSchema = z.enum(['tune', 'template', 'other']);
```suggestion
export const FilePurposeSchema = z.enum(['tune', 'template']);
```

2023-07-18 12:01 UTC, Tomas2D requested changes

2023-07-19 06:43 UTC, pilartomas commented on package.json
> +    "form-data": "^4.0.0",
CJS modules were dropped in `5.x`

2023-07-19 06:45 UTC, pilartomas commented on src/client-types.ts
> +  count: z.number().int().positive().nullish(),
This is not the resulting count but the desired count. It makes no sense to request zero items.

2023-07-19 06:46 UTC, pilartomas commented on src/client-types.ts
> +  count: z.number().int().positive().nullish(),
I should rename this to `ListInputSchema`

2023-07-19 06:48 UTC, pilartomas commented on src/helpers/types.ts
> +  : { [k in Key]?: false };
It doesn't allow for leaving out the key.

2023-07-19 06:52 UTC, pilartomas commented on package.json
> +    "form-data": "^4.0.0",
That's the latest version afaik https://www.npmjs.com/package/form-data

2023-07-19 07:01 UTC, pilartomas commented on src/api-types.ts
> +  totalCount: z.number().int().nonnegative(),
I was hoping for nicer error messages during parsing but apparently it is just an alias.

2023-07-19 11:04 UTC, Tomas2D commented on package.json
> +    "form-data": "^4.0.0",
I see; but maybe this package will be better https://www.npmjs.com/package/formdata-node

2023-07-19 11:06 UTC, Tomas2D commented on src/helpers/types.ts
> +  : { [k in Key]?: false };
I see.

2023-07-19 11:25 UTC, pilartomas commented on package.json
> +    "form-data": "^4.0.0",
I considered that one but it dropped CJS support in `5.x`.

2023-07-19 11:40 UTC, Tomas2D commented on src/client-types.ts
> +  count: z.number().int().positive().nullish(),
Yeah, please rename it.

2023-07-20 06:34 UTC, merged